# Data Directory

This directory contains all the data artifacts generated by the create dataset pipeline. It is structured chronologically, tracking the exact transformation of raw YouTube videos into fully processed, machine-learning-ready lip-reading datasets.

### Directory Structure

*   **`01_raw_videos/`**
    *   Contains the full `.mp4` videos downloaded from YouTube, standardized to 1080p and 25 FPS.
    *   Includes a `metadata.json` file storing source URLs and video details.
*   **`02_raw_transcripts/`**
    *   Contains `.json` files generated by WhisperX. 
    *   Holds the complete text transcripts, exact word-level timestamps, and speaker diarization (who spoke when) for each raw video.
*   **`03_frame_analysis/`**
    *   Contains `.json` files storing the analyzed facial landmarks for every single frame of the raw videos.
    *   The coordinates are extracted using MediaPipe, but these files store only the specific points needed (like lips) and validity flags (e.g., face visible, good head pose).
*   **`04_clips_dataset/`**
    *   This is the processed dataset containing the **valid segments** extracted from the raw videos.
    *   These segments (which can be sentences, phrases, or specific timeframes) represent parts of the video where a single speaker is clearly visible with a good head pose and speak.
    *   `videos/`: Contains short `.mp4` clips of full faces for these valid segments.
    *   `05_lips_videos/`: Contains short `.mp4` clips tightly cropped around the speaker's lips (e.g., 88x88) for the exact same segments.
    *   `labels/`: Contains the text transcripts and metadata mapping to each extracted clip.
*   **`06_single_words_dataset/`**
    *   This is the processed **word-level** dataset. 
    *   Contains extremely short `.mp4` lip-cropped videos representing single spoken words, extracted from the valid segments, alongside `.json` files storing their corresponding text labels.
*   **`07_statistics/`**
    *   Contains generated dataset statistics, distribution charts, and visual examples created for the final Kaggle dataset release.